name: CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.0]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.0
      - name: Install dependencies
        run: npm ci

      - name: run
        run: npm run test
      
      
