name: CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.0]
  steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: "npm"

        # 모듈 설치
        - name: Install modules
          run: npm install
        # testcode 실행
        - name: Run test codes
          run: npm run test
        # 빌드
        - name: Build project
          run: npm run build